imports


In [6]:
import numpy as np

tablica zer

In [7]:
zeroArray = np.zeros(10)
print(zeroArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


tablica piątek

In [14]:
zeroArray = np.ones(10) * 5
print(zeroArray)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


tablica od 10 do 50

In [13]:
tenToFiftyArray = np.arange(10, 51, 1)
print(tenToFiftyArray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


macierz 3x3 z liczbami od 0 do 8

In [16]:
zeroToEightMatrix = np.arange(0,9,1).reshape(3,3)
print(zeroToEightMatrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


macierz jednostkowa 3x3

In [17]:
identityMatrix = np.eye(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


macierz 5x5 z liczbami z dystrubucji normalnej Gaussa

In [18]:
gaussMatrix = np.random.normal(size=(5,5))
print(gaussMatrix)

[[ 0.33508819 -1.23177546 -0.48437584 -0.09981868  0.08775169]
 [ 0.15729039  0.48619297  0.25429212 -0.85166758  0.89165377]
 [ 0.63516708 -0.53724512 -0.16438212  0.41132014  0.50506788]
 [ 0.84011866  0.93831261  1.51276599  0.87041234 -0.50903913]
 [ 0.25372791  0.34774677  0.33993486  0.51401493 -0.56736601]]


macierz 10x10 z wartosciami od 0,01 do do 1 z krokiem 0,01

In [21]:
tenByTenMatrix = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(tenByTenMatrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


tablica rozlozona liniowo

In [22]:
linearArray = np.linspace(0,1,20)
print(linearArray)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#tablica z losowymi liczbami (1,25) - zamiana w macierz 5x5 i inne operacje

In [26]:
randomOneToTwentyFive = np.random.randint(1,26,25)
print("Tablica z losowymi liczbami od 1 do 25:\n", randomOneToTwentyFive)
matrix = randomOneToTwentyFive.reshape(5,5)
print("Macierz z takimi samymi wartościami:\n", matrix)
mean = randomOneToTwentyFive.mean()
print("Średnia wartości: ", mean)
sum = randomOneToTwentyFive.sum()
print("Suma wartości: ", sum)
standardDeviation = randomOneToTwentyFive.std()
print("Odchylenie standardowe: ", standardDeviation)


Tablica z losowymi liczbami od 1 do 25:
 [15 11 25 20  6  7 22  7  5  1 19 20  6 24 10 18 10 20 10 23 17  5  5 21
 17]
Macierz z takimi samymi wartościami:
 [[15 11 25 20  6]
 [ 7 22  7  5  1]
 [19 20  6 24 10]
 [18 10 20 10 23]
 [17  5  5 21 17]]


tablica z losowymi wartoscami od 1 do 100 - mediana, min, max

In [53]:
randomMatrix = np.random.randint(1,100,25).reshape(5,5)
print("Macierz", randomMatrix)
median = np.median(randomMatrix)
print("mediana: ", median)
min = np.min(randomMatrix)
print("minimum: ", min)
max = np.max(randomMatrix)
print("maximum: ", max)


Macierz [[26 98 99 18  3]
 [44 64 37 87 27]
 [59 19 45 23  7]
 [54  7 26 96 85]
 [79 58  4 27 90]]
mediana:  44.0
minimum:  3
maximum:  99


losowe liczby - transpozycja

In [ ]:
def set_y():
    y_axis = np.random.randint(2, 11)
    if y_axis != x:
        return y_axis
    else:
        y_axis = set_y()
        return y_axis


x = np.random.randint(2, 11)
y = set_y()
randomNumbersRandomAxis = np.random.randint(0, 101, (x, y))
print("losowe liczby z losowa osia:\n", randomNumbersRandomAxis)
print("transpozycja:\n", randomNumbersRandomAxis.transpose())

dodawanie macierzy

In [ ]:
tableX = np.random.randint(2, 17)
tableY = np.random.randint(2, 17)
matrixA = np.random.randint(0, 101, (tableX, tableY))
print("macierz A + macierz B:\n", matrixA, "\n")
matrixB = np.random.randint(0, 101, (tableX, tableY))
print("macierz A + macierz B:\n", matrixB, "\n")
print("macierz A + macierz B:\n", matrixA + matrixB, "\n")

mnozenie macierzy

In [ ]:
matrixXMultiply = np.random.randint(2, 15)
matrixYMultiply = np.random.randint(2, 15)
matrixAMultiply = np.random.randint(0, 101, (matrixXMultiply, matrixYMultiply))
print("Macierz A do pomnożenia:\n", matrixAMultiply, "\n")
matrixBMultiply = np.random.randint(0, 101, (matrixYMultiply, matrixXMultiply))
print("Macierz B do pomnożenia:\n", matrixBMultiply, "\n")
print("Macierz A * Macierz B - np.matmul():\n", np.matmul(matrixAMultiply, matrixBMultiply))
print("Macierz A * Macierz B - np.dot():\n", np.dot(matrixAMultiply, matrixBMultiply))

In [54]:
def set_y():
    y_axis = np.random.randint(2, 11)
    if y_axis != x:
        return y_axis
    else:
        y_axis = set_y()
        return y_axis


x = np.random.randint(2, 11)
y = set_y()
randomNumbersRandomAxis = np.random.randint(0, 101, (x, y))
print("losowe liczby z losowa osia:\n", randomNumbersRandomAxis)
print("transpozycja:\n", randomNumbersRandomAxis.transpose())

losowe liczby z losowa osia:
 [[ 35  76  67  42  90  85  45]
 [ 73   2  77  72  94  45  83]
 [ 92  65  79  74  74  26  39]
 [  9  49  49  10  50  32  11]
 [ 53 100  25  37  61  46  61]
 [ 48  19  61  26  42  73  93]
 [ 86  39  95  66  81  61  57]
 [  8  57  53  23  31  10  56]
 [ 29  33  66  33  89  90  91]
 [ 52  87   3  98  88  82  96]]
transpozycja:
 [[ 35  73  92   9  53  48  86   8  29  52]
 [ 76   2  65  49 100  19  39  57  33  87]
 [ 67  77  79  49  25  61  95  53  66   3]
 [ 42  72  74  10  37  26  66  23  33  98]
 [ 90  94  74  50  61  42  81  31  89  88]
 [ 85  45  26  32  46  73  61  10  90  82]
 [ 45  83  39  11  61  93  57  56  91  96]]


dodawanie macierzy

In [64]:
tableX = np.random.randint(2, 17)
tableY = np.random.randint(2, 17)
matrixA = np.random.randint(0, 101, (tableX, tableY))
print("macierz A + macierz B:\n", matrixA, "\n")
matrixB = np.random.randint(0, 101, (tableX, tableY))
print("macierz A + macierz B:\n", matrixB, "\n")
print("macierz A + macierz B:\n", matrixA + matrixB, "\n")

macierz A + macierz B:
 [[  1  40  55  88  18  54]
 [ 18  86  80  29  23  21]
 [ 17  50  12  51  46  58]
 [ 93  45  81  34  53   4]
 [ 58  37  87  79  14  42]
 [100   7  26  66  77  68]
 [ 25  38  21  14  68  36]
 [ 94  13  29  36  74  23]
 [ 25  94  93  97  72  34]
 [ 80  92  10  55  22  76]
 [ 10  94  56  86  84   6]
 [ 42  77  21  70   1  76]
 [ 24  67  57  40  92  51]
 [ 48  46  30  40  45  51]
 [ 88  95  91  63  98  18]] 

macierz A + macierz B:
 [[ 21  64  62  51  99  49]
 [ 26  87  32  94  80  43]
 [ 32  99  95  61  26  95]
 [  7  70  52  66  20  99]
 [ 58  96  30  90  28  17]
 [ 99  86  73  98   1   0]
 [ 76  48  79  28  87  16]
 [  4  59   8  34  29  90]
 [ 68  22  96  51  56  47]
 [ 83  10  17  43  66   1]
 [ 65  90  57  11   3  90]
 [ 79  36  31  32  56  50]
 [ 64  57  31 100  73  77]
 [  2  41  50  33  70  45]
 [ 17  81  61  45  58  47]] 

macierz A + macierz B:
 [[ 22 104 117 139 117 103]
 [ 44 173 112 123 103  64]
 [ 49 149 107 112  72 153]
 [100 115 133 100  73 103]
 [11

mnozenie macierzy

In [65]:
matrixXMultiply = np.random.randint(2, 15)
matrixYMultiply = np.random.randint(2, 15)
matrixAMultiply = np.random.randint(0, 101, (matrixXMultiply, matrixYMultiply))
print("Macierz A do pomnożenia:\n", matrixAMultiply, "\n")
matrixBMultiply = np.random.randint(0, 101, (matrixYMultiply, matrixXMultiply))
print("Macierz B do pomnożenia:\n", matrixBMultiply, "\n")
print("Macierz A * Macierz B - np.matmul():\n", np.matmul(matrixAMultiply, matrixBMultiply))
print("Macierz A * Macierz B - np.dot():\n", np.dot(matrixAMultiply, matrixBMultiply))

Macierz A do pomnożenia:
 [[73 56]
 [98 14]
 [99 18]
 [ 5 22]
 [31 78]] 

Macierz B do pomnożenia:
 [[ 14  91  40  65  61]
 [ 77   1 100  53   6]] 

Macierz A * Macierz B - np.matmul():
 [[5334 6699 8520 7713 4789]
 [2450 8932 5320 7112 6062]
 [2772 9027 5760 7389 6147]
 [1764  477 2400 1491  437]
 [6440 2899 9040 6149 2359]]
Macierz A * Macierz B - np.dot():
 [[5334 6699 8520 7713 4789]
 [2450 8932 5320 7112 6062]
 [2772 9027 5760 7389 6147]
 [1764  477 2400 1491  437]
 [6440 2899 9040 6149 2359]]
